export type ServiceProvider = {
  id: string;
  categoryId: string;
  name: string;
  headline: string;
  rating: number;
  reviews: number;
  location: string;
  avatar: string;
  bio: string;
  tags: string[];
};

export const SERVICE_PROVIDERS: ServiceProvider[] = [
  {
    id: "ana-rivera",
    categoryId: "tecnologia-desarrollo",
    name: "Ana Rivera",
    headline: "Full Stack Developer · React & Node",
    rating: 4.9,
    reviews: 42,
    location: "Remoto · Buenos Aires",
    avatar: "👩‍💻",
    bio: "Desarrollo plataformas web escalables con foco en performance y DX.",
    tags: ["React", "Node.js", "UX"],
  },
  {
    id: "martin-costa",
    categoryId: "tecnologia-desarrollo",
    name: "Martín Costa",
    headline: "Soporte IT onsite & remoto",
    rating: 4.7,
    reviews: 31,
    location: "CABA",
    avatar: "🛠️",
    bio: "Resuelvo incidencias críticas y diseño planes de continuidad para PYMES.",
    tags: ["Soporte", "Infraestructura"],
  },
  {
    id: "lucia-ortega",
    categoryId: "diseno-creatividad",
    name: "Lucía Ortega",
    headline: "Branding estratégico y UI Systems",
    rating: 5,
    reviews: 27,
    location: "Remoto",
    avatar: "🎨",
    bio: "Construyo identidades sólidas y sistemas UI listos para escalar.",
    tags: ["Branding", "UI Kits"],
  },
  {
    id: "diego-ferrari",
    categoryId: "diseno-creatividad",
    name: "Diego Ferrari",
    headline: "Ilustrador editorial & motion básico",
    rating: 4.8,
    reviews: 18,
    location: "Rosario",
    avatar: "✏️",
    bio: "Visual storytelling para editoriales y contenidos digitales.",
    tags: ["Ilustración", "Motion"],
  },
  {
    id: "federica-suarez",
    categoryId: "marketing-publicidad",
    name: "Federica Suárez",
    headline: "Paid Media Specialist · Meta & Google",
    rating: 4.9,
    reviews: 39,
    location: "Montevideo",
    avatar: "📊",
    bio: "Estrategias de adquisición y optimización de funnels.",
    tags: ["Ads", "Analytics"],
  },
  {
    id: "santiago-rios",
    categoryId: "marketing-publicidad",
    name: "Santiago Ríos",
    headline: "Content & Community Manager",
    rating: 4.6,
    reviews: 22,
    location: "Córdoba",
    avatar: "📝",
    bio: "Planificación y ejecución de contenidos con voz auténtica.",
    tags: ["Social Media", "Copywriting"],
  },
  {
    id: "valentina-nadal",
    categoryId: "fotografia-video",
    name: "Valentina Nadal",
    headline: "Fotografía lifestyle & campañas",
    rating: 5,
    reviews: 33,
    location: "Mar del Plata",
    avatar: "📷",
    bio: "Produzco shootings de marca con estética moderna y natural.",
    tags: ["Fotografía", "Edición"],
  },
  {
    id: "leonardo-quiroga",
    categoryId: "fotografia-video",
    name: "Leonardo Quiroga",
    headline: "Filmmaker para eventos y cápsulas",
    rating: 4.8,
    reviews: 19,
    location: "La Plata",
    avatar: "🎥",
    bio: "Cobertura integral en video con entrega express.",
    tags: ["Video", "Eventos"],
  },
  {
    id: "camila-arias",
    categoryId: "reparaciones-mantenimiento",
    name: "Camila Arias",
    headline: "Electricista matriculada",
    rating: 4.9,
    reviews: 54,
    location: "Zona Norte GBA",
    avatar: "⚡",
    bio: "Instalaciones seguras y mantenimiento preventivo para hogares.",
    tags: ["Electricidad", "Domótica"],
  },
  {
    id: "gustavo-fuentes",
    categoryId: "reparaciones-mantenimiento",
    name: "Gustavo Fuentes",
    headline: "Servicio técnico integral",
    rating: 4.5,
    reviews: 41,
    location: "CABA",
    avatar: "🔧",
    bio: "Soluciones rápidas para electrodomésticos y climatización.",
    tags: ["Reparación", "Climatización"],
  },
  {
    id: "paula-mendez",
    categoryId: "construccion-remodelacion",
    name: "Paula Méndez",
    headline: "Arquitecta · Reformas interiores",
    rating: 4.9,
    reviews: 28,
    location: "CABA",
    avatar: "🏡",
    bio: "Proyectos llave en mano con visión funcional y estética.",
    tags: ["Arquitectura", "Interiorismo"],
  },
  {
    id: "matias-bulacio",
    categoryId: "construccion-remodelacion",
    name: "Matías Bulacio",
    headline: "Maestro mayor de obras",
    rating: 4.6,
    reviews: 35,
    location: "San Isidro",
    avatar: "🧱",
    bio: "Remodelaciones estructurales y ampliaciones seguras.",
    tags: ["Obra", "Remodelación"],
  },
  {
    id: "rocio-salvatierra",
    categoryId: "salud-bienestar",
    name: "Rocío Salvatierra",
    headline: "Personal trainer & movilidad",
    rating: 5,
    reviews: 44,
    location: "Palermo",
    avatar: "🏋️",
    bio: "Planes personalizados con seguimiento integral.",
    tags: ["Fitness", "Movilidad"],
  },
  {
    id: "nicolas-baeza",
    categoryId: "salud-bienestar",
    name: "Nicolás Baeza",
    headline: "Masajista deportivo",
    rating: 4.8,
    reviews: 26,
    location: "Belgrano",
    avatar: "💆",
    bio: "Recuperación muscular y bienestar post entrenamiento.",
    tags: ["Masajes", "Recuperación"],
  },
  {
    id: "mariana-galvez",
    categoryId: "educacion-tutorias",
    name: "Mariana Gálvez",
    headline: "Profesora de inglés y TOEFL coach",
    rating: 5,
    reviews: 37,
    location: "Remoto",
    avatar: "🗣️",
    bio: "Clases conversacionales con foco en pronunciación.",
    tags: ["Inglés", "TOEFL"],
  },
  {
    id: "facundo-frias",
    categoryId: "educacion-tutorias",
    name: "Facundo Frías",
    headline: "Tutoría matemática secundaria",
    rating: 4.7,
    reviews: 21,
    location: "Lanús",
    avatar: "➗",
    bio: "Explicaciones claras y guías para exámenes.",
    tags: ["Matemática", "Apoyo escolar"],
  },
  {
    id: "brenda-rios",
    categoryId: "belleza-estetica",
    name: "Brenda Ríos",
    headline: "Beauty artist · maquillaje social",
    rating: 4.9,
    reviews: 46,
    location: "Recoleta",
    avatar: "💄",
    bio: "Looks personalizados para eventos y sesiones.",
    tags: ["Makeup", "Eventos"],
  },
  {
    id: "agus-fernandez",
    categoryId: "belleza-estetica",
    name: "Agus Fernández",
    headline: "Manicurista especializada en nail art",
    rating: 4.8,
    reviews: 29,
    location: "Villa Urquiza",
    avatar: "💅",
    bio: "Diseños exclusivos y servicios a domicilio.",
    tags: ["Nail Art", "Gel"],
  },
  {
    id: "joaquin-coria",
    categoryId: "eventos-entretenimiento",
    name: "Joaquín Coria",
    headline: "DJ & productor musical",
    rating: 5,
    reviews: 25,
    location: "Córdoba",
    avatar: "🎧",
    bio: "Sets personalizados para bodas y eventos corporativos.",
    tags: ["DJ", "Eventos"],
  },
  {
    id: "mila-paredes",
    categoryId: "eventos-entretenimiento",
    name: "Mila Paredes",
    headline: "Planner de eventos boutique",
    rating: 4.9,
    reviews: 32,
    location: "CABA",
    avatar: "🗓️",
    bio: "Organización integral con foco en experiencias memorables.",
    tags: ["Eventos", "Decoración"],
  },
  {
    id: "gerardo-cabral",
    categoryId: "legales-contables",
    name: "Gerardo Cabral",
    headline: "Abogado laboral & corporativo",
    rating: 4.8,
    reviews: 34,
    location: "Microcentro",
    avatar: "📑",
    bio: "Asesoría y representación preventiva para pymes.",
    tags: ["Legal", "Laboral"],
  },
  {
    id: "sofia-llanos",
    categoryId: "legales-contables",
    name: "Sofía Llanos",
    headline: "Contadora · impuestos & finanzas",
    rating: 4.9,
    reviews: 30,
    location: "Remoto",
    avatar: "🧾",
    bio: "Planificación tributaria y reportes financieros claros.",
    tags: ["Contable", "Impuestos"],
  },
  {
    id: "manuel-olmos",
    categoryId: "transporte-mensajeria",
    name: "Manuel Olmos",
    headline: "Mudanzas express con seguro",
    rating: 4.7,
    reviews: 40,
    location: "Zona Oeste",
    avatar: "🚛",
    bio: "Equipos preparados para mudanzas residenciales y oficinas.",
    tags: ["Mudanzas", "Express"],
  },
  {
    id: "naty-vazquez",
    categoryId: "transporte-mensajeria",
    name: "Naty Vázquez",
    headline: "Mensajería en moto · CABA",
    rating: 4.8,
    reviews: 23,
    location: "CABA",
    avatar: "🏍️",
    bio: "Gestiones urgentes y retiros programados en horario extendido.",
    tags: ["Mensajería", "Express"],
  },
  {
    id: "lola-andres",
    categoryId: "mascotas-animales",
    name: "Lola Andrés",
    headline: "Paseos caninos personalizados",
    rating: 4.9,
    reviews: 36,
    location: "Caballito",
    avatar: "🐶",
    bio: "Circuitos adaptados según energía y necesidades.",
    tags: ["Paseos", "Adiestramiento"],
  },
  {
    id: "ramiro-senna",
    categoryId: "mascotas-animales",
    name: "Ramiro Senna",
    headline: "Entrenador canino positivo",
    rating: 4.8,
    reviews: 27,
    location: "Nuñez",
    avatar: "🐕",
    bio: "Programas de obediencia y socialización respetuosa.",
    tags: ["Entrenamiento", "Conducta"],
  },
  {
    id: "clarisa-bellusci",
    categoryId: "limpieza-hogar",
    name: "Clarisa Bellusci",
    headline: "Limpieza profunda residencial",
    rating: 5,
    reviews: 48,
    location: "Quilmes",
    avatar: "🧼",
    bio: "Equipos y productos propios, enfoque eco-friendly.",
    tags: ["Limpieza", "Eco"],
  },
  {
    id: "veronica-juarez",
    categoryId: "limpieza-hogar",
    name: "Verónica Juárez",
    headline: "Organización de espacios & niñera",
    rating: 4.7,
    reviews: 24,
    location: "San Telmo",
    avatar: "🧺",
    bio: "Organización integral y cuidado confiable para familias.",
    tags: ["Organización", "Niñera"],
  },
];
