export type ServiceProvider = {
  id: string;
  categoryId: string;
  name: string;
  headline: string;
  rating: number;
  reviews: number;
  location: string;
  avatar: string;
  bio: string;
  tags: string[];
};

export const SERVICE_PROVIDERS: ServiceProvider[] = [
  {
    id: "ana-rivera",
    categoryId: "tecnologia-desarrollo",
    name: "Ana Rivera",
    headline: "Desarrolladora full stack freelance",
    rating: 4.9,
    reviews: 42,
    location: "Buenos Aires",
    avatar: "👩‍💻",
    bio: "Creo aplicaciones web livianas usando React, Node y buenas prácticas accesibles.",
    tags: ["React", "Node", "UI"],
  },
  {
    id: "martin-costa",
    categoryId: "tecnologia-desarrollo",
    name: "Martín Costa",
    headline: "Soporte técnico a domicilio",
    rating: 4.7,
    reviews: 31,
    location: "CABA",
    avatar: "🛠️",
    bio: "Instalo redes hogareñas y doy mantenimiento preventivo para que nada se detenga.",
    tags: ["Soporte", "Redes"],
  },
  {
    id: "lucia-ortega",
    categoryId: "diseno-creatividad",
    name: "Lucía Ortega",
    headline: "Diseñadora de marca y UI kits",
    rating: 5,
    reviews: 27,
    location: "Remoto",
    avatar: "🎨",
    bio: "Trabajo identidad visual completa con entregables listos para desarrollo.",
    tags: ["Branding", "UI"],
  },
  {
    id: "federica-suarez",
    categoryId: "marketing-publicidad",
    name: "Federica Suárez",
    headline: "Paid media para pymes",
    rating: 4.9,
    reviews: 39,
    location: "Montevideo",
    avatar: "📣",
    bio: "Lanzo campañas simples de medir en Meta y Google con foco en conversiones.",
    tags: ["Ads", "Estrategia"],
  },
  {
    id: "valentina-nadal",
    categoryId: "fotografia-video",
    name: "Valentina Nadal",
    headline: "Fotógrafa lifestyle y producto",
    rating: 5,
    reviews: 33,
    location: "Mar del Plata",
    avatar: "📸",
    bio: "Organizo shootings ágiles con entrega editada en menos de 72 horas.",
    tags: ["Fotografía", "Edición"],
  },
  {
    id: "camila-arias",
    categoryId: "reparaciones-mantenimiento",
    name: "Camila Arias",
    headline: "Electricista matriculada",
    rating: 4.9,
    reviews: 54,
    location: "Zona Norte",
    avatar: "⚡",
    bio: "Realizo instalaciones seguras y tableros con certificación vigente.",
    tags: ["Electricidad", "Hogar"],
  },
  {
    id: "hugo-lamas",
    categoryId: "construccion-remodelacion",
    name: "Hugo Lamas",
    headline: "Maestro mayor de obras",
    rating: 4.8,
    reviews: 21,
    location: "La Plata",
    avatar: "🏗️",
    bio: "Coordino remodelaciones pequeñas asegurando limpieza diaria y tiempos claros.",
    tags: ["Remodelación", "Planos"],
  },
  {
    id: "tamara-gil",
    categoryId: "salud-bienestar",
    name: "Tamara Gil",
    headline: "Entrenadora funcional",
    rating: 4.9,
    reviews: 45,
    location: "Cordoba",
    avatar: "🧘",
    bio: "Entrenamientos personalizados en casa o parque con planes semanales fáciles.",
    tags: ["Funcional", "Rutinas"],
  },
  {
    id: "pablo-nunez",
    categoryId: "educacion-tutorias",
    name: "Pablo Núñez",
    headline: "Profesor de matemáticas online",
    rating: 4.8,
    reviews: 28,
    location: "Remoto",
    avatar: "📚",
    bio: "Preparación para parciales y apoyo continuo con ejercicios resueltos.",
    tags: ["Matemática", "Secundario"],
  },
  {
    id: "sofia-vidal",
    categoryId: "belleza-estetica",
    name: "Sofía Vidal",
    headline: "Estilista integral y nail art",
    rating: 4.9,
    reviews: 37,
    location: "Rosario",
    avatar: "💅",
    bio: "Servicio a domicilio con materiales hipoalergénicos y diseños personalizados.",
    tags: ["Manicura", "Peluquería"],
  },
  {
    id: "leonel-dj",
    categoryId: "eventos-entretenimiento",
    name: "Leonel DJ",
    headline: "DJ para fiestas privadas",
    rating: 4.7,
    reviews: 19,
    location: "Buenos Aires",
    avatar: "🎉",
    bio: "Armo playlists a medida y ofrezco equipo de sonido básico incluido.",
    tags: ["DJ", "Eventos"],
  },
  {
    id: "mariana-torres",
    categoryId: "legales-contables",
    name: "Mariana Torres",
    headline: "Abogada laboral simple",
    rating: 5,
    reviews: 16,
    location: "Buenos Aires",
    avatar: "⚖️",
    bio: "Asesoría express por videollamada con pasos claros para reclamos.",
    tags: ["Laboral", "Consultas"],
  },
  {
    id: "carlos-perez",
    categoryId: "transporte-mensajeria",
    name: "Carlos Pérez",
    headline: "Fletes y mudanzas chicas",
    rating: 4.8,
    reviews: 48,
    location: "GBA",
    avatar: "🚚",
    bio: "Traslados puerta a puerta con ayuda para cargar y asegurar tus cosas.",
    tags: ["Mudanzas", "Logística"],
  },
  {
    id: "brenda-pets",
    categoryId: "mascotas-animales",
    name: "Brenda Pets",
    headline: "Paseadora y cuidadora",
    rating: 4.9,
    reviews: 52,
    location: "Palermo",
    avatar: "🐾",
    bio: "Paseos diarios y guardería de fin de semana con fotos y reportes.",
    tags: ["Paseos", "Guardería"],
  },
  {
    id: "laura-clean",
    categoryId: "limpieza-hogar",
    name: "Laura Clean",
    headline: "Limpieza por hora",
    rating: 4.8,
    reviews: 40,
    location: "Vicente López",
    avatar: "🧽",
    bio: "Servicio prolijo, llevo mis productos y organizo ambientes pequeños.",
    tags: ["Limpieza", "Organización"],
  },
];
